-->
    <div class="goodat" id="getSec">
    	<h1><img src="/templets/jq/images/goddat3.jpg" />在线问诊</h1>
        <div class="onlinei ">
        	<div class="btt"><a href="#">精神运动发育迟...</a> <b>密</b>  <span>共23条对话 今天</span></div>
            <p class="add">疾病：精神运动发育迟滞  <span>广东 深圳</span></p>
            <p class="gray">交流涉及隐私，仅医患本人可见</p>
        </div>
        <div class="onlinei onlineit">
        	<div class="btt"><a href="#">言语表达不清门...</a> <b>名医挂号</b>  <span>共23条对话 今天</span></div>
            <p class="add">疾病：精神运动发育迟滞  <span>广东 深圳</span></p>
        </div>
        <div class="onlinei onlineit">
        	<div class="btt"><a href="#">精神运动发育迟...</a> <b>密</b>  <span>共23条对话 今天</span></div>
            <p class="add">疾病：精神运动发育迟滞  <span>广东 深圳</span></p>
            <p class="gray">交流涉及隐私，仅医患本人可见</p>
        </div>
    </div>
    <!--