<div class="goodat">
    	<h1><img src="/templets/jq/images/goddat.jpg" />专业擅长</h1>
        <p>
            [field:scly /]
        </p>
    </div>
    <div class="goodat">
    	<h1><img src="/templets/jq/images/goddat1.jpg" />执业经历</h1>
        	[field:zyjl /]
            <p class="time"><img src="/templets/jq/images/time.jpg" />出诊时间：[field:czsj /]</p>
    	<p class="tips">温馨提示：为保证就诊质量，专家每次出诊，限号十名</p>
        <div><input name="" value="在线咨询" class="zx gbutton" type="button" /><input name="" value="预约挂号" class="gh gbutton"  type="button" /></div>
        <div class="clear"></div>
    </div>