<?php
$z[0]=Array("field","",88,117);
$z[0][4]=array();
$z[0][4]['name']="typename";
$z[1]=Array("arclist","\r\n        <div class=\"onlinei onlineit\">\r\n        	<div class=\"btt\"><a href=\"#\">[field:title/]</a> <b>密</b>  <span>共23条对话 今天</span></div>\r\n            <p class=\"add\">[field:description function='cn_substr(Html2text(\"@me\").\"...\",30)'/]<span>[field:shorttitle/]</span></p>\r\n            <p class=\"gray\">交流涉及隐私，仅医患本人可见</p>\r\n        </div>\r\n        ",132,583);
$z[1][4]=array();
$z[1][4]['row']="3";
$z[1][4]['orderby']="pubdate";
$z[1][4]['title']="8";

?>