
<field:bbxm itemname="宝宝姓名" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:bbxm>

<field:bbxb itemname="宝宝性别" autofield="1" type="select" isnull="true" default="男,女"  maxlength="250" page="">
</field:bbxb>


<field:bbnl itemname="宝宝年龄" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:bbnl>

<field:pgzz itemname="疾病症状" autofield="1" type="multitext" isnull="true" default=""  maxlength="250" page="">
</field:pgzz>


<field:jzxm itemname="家长姓名" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:jzxm>

<field:lxfs itemname="联系方式" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:lxfs>

