
<field:zhicheng1 itemname="职称1" autofield="1" notsend="0" type="textchar" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:zhicheng1>


<field:zhicheng2 itemname="职称2" autofield="1" notsend="0" type="textchar" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:zhicheng2>


<field:zhicheng3 itemname="职称3" autofield="1" notsend="0" type="text" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:zhicheng3>

<field:zhiliao itemname="治疗" autofield="1" notsend="0" type="htmltext" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:zhiliao>

<field:yufang itemname="预防" autofield="1" notsend="0" type="htmltext" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:yufang>
