<field:body itemname="文章内容" autofield="0" notsend="0" type="htmltext" isnull="true" islist="1" default=""  maxlength="" page="split">	
</field:body>	

<field:bingyin itemname="病因" autofield="1" notsend="0" type="multitext" isnull="true" islist="1" default=""  maxlength="1000" page="split">
</field:bingyin>


<field:linchuangbiaoxian itemname="临床表现" autofield="1" notsend="0" type="multitext" isnull="true" islist="1" default=""  maxlength="1000" page="split">
</field:linchuangbiaoxian>


<field:jiancha itemname="检查" autofield="1" notsend="0" type="multitext" isnull="true" islist="1" default=""  maxlength="1000" page="split">
</field:jiancha>


<field:zhenduan itemname="诊断" autofield="1" notsend="0" type="text" isnull="true" islist="1" default=""  maxlength="1000" page="split">
</field:zhenduan>
