<?php
$z[0]=Array("arcurl","",80,95);
$z[0][4]=array();
$z[1]=Array("picname","",107,123);
$z[1][4]=array();
$z[2]=Array("title","",233,247);
$z[2][4]=array();
$z[3]=Array("pubdate","",340,383);
$z[3][4]=array();
$z[3][4]['function']="GetDateMK(@me)";
$z[4]=Array("click","",477,491);
$z[4][4]=array();
$z[5]=Array("description","",591,660);
$z[5][4]=array();
$z[5][4]['function']="cn_substr(Html2text(\"@me\").\"...\",100)";

?>