<?php
$z[0]=Array("arcurl","",56,71);
$z[0][4]=array();
$z[1]=Array("picname","",128,144);
$z[1][4]=array();
$z[2]=Array("title","",250,264);
$z[2][4]=array();
$z[3]=Array("pubdate","",357,400);
$z[3][4]=array();
$z[3][4]['function']="GetDateMK(@me)";
$z[4]=Array("click","",494,508);
$z[4][4]=array();
$z[5]=Array("description","",608,677);
$z[5][4]=array();
$z[5][4]['function']="cn_substr(Html2text(\"@me\").\"...\",100)";

?>