<?php
$z[0]=Array("field","",88,117);
$z[0][4]=array();
$z[0][4]['name']="typename";
$z[1]=Array("arclist","\r\n        <div class=\"onlinei onlineit\">\r\n        	<div class=\"btt\">\r\n            	<a href=\"javascript:void(0)\" onclick=\"openZoosUrl('chatwin');\">[field:title/]</a> \r\n                <b class=\"mimi\"></b>  \r\n                <span>共<em class=\"random1\" style=\"font-style: normal;\"></em>条对话 今天</span>\r\n            </div>\r\n            <p class=\"add\">[field:description function='cn_substr(Html2text(\"@me\").\"...\",30)'/]<span>[field:shorttitle/]</span></p>\r\n            <p class=\"gray mi_yinsi\" style=\"display:none\" >交流涉及隐私，仅医患本人可见</p>\r\n        </div>\r\n        ",132,792);
$z[1][4]=array();
$z[1][4]['row']="3";
$z[1][4]['orderby']="rand";
$z[1][4]['titlelen']="18";

?>