<field:body itemname="文章内容" autofield="0" notsend="0" type="htmltext" isnull="true" islist="1" default=""  maxlength="" page="split">	
</field:body>	
<field:ys itemname="医生" autofield="1" notsend="0" type="text" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:ys>

<field:tjycrd itemname="推荐or原创or热点" autofield="1" notsend="0" type="textchar" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:tjycrd>

