<?php
$z[0]=Array("field","",76,105);
$z[0][4]=array();
$z[0][4]['name']="typename";
$z[1]=Array("arclist","\r\n        <div class=\"patientr\">\r\n        	<dl>\r\n            	<dt><img src=\"/templets/jq/images/partientr.jpg\" /></dt>\r\n                <dd><span class=\"l\">[field:shorttitle/]</span>	<span class=\"r\">昨天13:48</span></dd>\r\n                <dd>[field:title/]</dd>\r\n                <div class=\"clear\"></div>\r\n            </dl>\r\n            <div class=\"clear\"></div>\r\n            <p>患者主观疗效：<b>很满意</b>　　态度：<b>很满意</b> </p>\r\n            <p>[field:description function='cn_substr(Html2text(\"@me\").\"...\",140)'/]</p>\r\n        </div>\r\n        ",120,727);
$z[1][4]=array();
$z[1][4]['row']="3";

?>