<img src="[field:picname/]">
							<div class="zjtd_art">
								<div class="zjtd_upper">
									<div class="zjtd_names" href="">
										<div>[field:title /]</div>
										<div>
											<p>[field:zhicheng1 function='cn_substr(@me,16)/]</p>
											<p>[field:zhicheng2 function='cn_substr(@me,16)/]</p>
											<p>[field:zhicheng3 function='cn_substr(@me,16)/]</p>
										</div>
									</div>
									<div class="zjtd_des">
										<div><img src="/templets/jq/images/dian.png" />[field:rongyu1 function='cn_substr(@me,43)'/]</div>
										<div><img src="/templets/jq/images/dian.png" />[field:rongyu2 function='cn_substr(@me,43)'/]</div>
										<div><img src="/templets/jq/images/dian.png" />[field:rongyu3 function='cn_substr(@me,43)'/]</div>
									</div>
									<div class="zjtd_swt">
										<a href="javascript:void(0)" onclick="openZoosUrl('chatwin');">
											<img src="/templets/jq/images/zjtd_gh.png">
											预约挂号
										</a>
										<a>
											<img src="/templets/jq/images/zjtd_zx.png">
											了解详情
										</a>
									</div>
								</div>
								<div class="zjtd_under">
									<div>
										<p>擅长</p>
										<p>领域</p>
									</div>
									<div>
										[field:scly function='cn_substr(@me,240)' /]
									</div>
								</div>
                                <div class="zjtd_time">
                                	<div>出诊时间：<span>[field:czsj function='cn_substr(@me,16)/]</span></div>
                                    <div>挂号费：<span>[field:ghf function='cn_substr(@me,16)/]</span></div>
                                </div>
                                
							</div>