
<field:zhicheng1 itemname="职称1" autofield="1" notsend="0" type="text" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:zhicheng1>

<field:zhicheng2 itemname="职称2" autofield="1" notsend="0" type="text" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:zhicheng2>

<field:zhicheng3 itemname="职称3" autofield="1" notsend="0" type="text" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:zhicheng3>

<field:rongyu1 itemname="荣誉1" autofield="1" notsend="0" type="text" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:rongyu1>

<field:rongyu2 itemname="荣誉2" autofield="1" notsend="0" type="text" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:rongyu2>
