<?php
$z[0]=Array("field","",500,519);
$z[0][4]=array();
$z[0][4]['name']="title";
$z[1]=Array("global","",520,546);
$z[1][4]=array();
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",623,645);
$z[2][4]=array();
$z[2][4]['name']="keywords";
$z[3]=Array("field","",710,762);
$z[3][4]=array();
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("arclist"," \r\n			<div class=\"content_disease\">\r\n				<div class=\"disease_tit\">病因</div>\r\n				<div class=\"disease_cont\">\r\n					[field:bingyin /]\r\n				</div>\r\n			</div>\r\n            ",2427,2689);
$z[4][4]=array();
$z[4][4]['addfields']="bingyin";
$z[4][4]['channelid']="18";
$z[4][4]['row']="10";
$z[4][4]['orderby']="pubdate";

?>