<li class="yndt_allList" >
                    	<div class="list_img"><a href="[field:arcurl/]"><img src="[field:picname/]" /></a></div>
                        <div class="list_cont">
                        	<p class="list_tit"><a href="[field:arcurl/]">[field:title/]</a></p>
                            <p class="list_intro">
                            	<span>[field:pubdate function='GetDateMK(@me)' /]</span>
                                <span><img src="/templets/jq/images/yndt_list.png" />[field:click/]人已读</span>
                            </p>
                            <p class="list_des">
                            	<a href="[field:arcurl/]">[field:description function='cn_substr(Html2text("@me")."...",100)'/]...</a>
                            </p>
                        </div>
                    </li>