<?php
$z[0]=Array("arcurl","",60,75);
$z[0][4]=array();
$z[1]=Array("picname","",133,149);
$z[1][4]=array();
$z[2]=Array("title","",255,269);
$z[2][4]=array();
$z[3]=Array("pubdate","",362,405);
$z[3][4]=array();
$z[3][4]['function']="GetDateMK(@me)";
$z[4]=Array("click","",499,513);
$z[4][4]=array();
$z[5]=Array("description","",613,682);
$z[5][4]=array();
$z[5][4]['function']="cn_substr(Html2text(\"@me\").\"...\",100)";

?>