
<field:bingyin itemname="病因" autofield="1" notsend="0" type="multitext" isnull="true" islist="1" default=""  maxlength="1000" page="split">
</field:bingyin>


<field:linchuangbiaoxian itemname="临床表现" autofield="1" notsend="0" type="multitext" isnull="true" islist="1" default=""  maxlength="1000" page="split">
</field:linchuangbiaoxian>

<field:jiancha itemname="检查" autofield="1" notsend="0" type="multitext" isnull="true" islist="1" default=""  maxlength="1000" page="split">
</field:jiancha>
