<?php
$z[0]=Array("picname","",10,26);
$z[0][4]=array();
$z[1]=Array("title","",153,168);
$z[1][4]=array();
$z[2]=Array("zhicheng1</p>","",207,471);
$z[2][4]=array();
$z[2][4]['<p>[field:zhicheng2</p> <p>[field:zhicheng3</p> </div> </div> <div class']="zjtd_des";
$z[2][4]['> <div><img src']="/templets/jq/images/dian.png";
$z[2][4]['/>[field:rongyu1 function']="cn_substr(@me,43)";
$z[3]=Array("rongyu2","",536,581);
$z[3][4]=array();
$z[3][4]['function']="cn_substr(@me,43)";
$z[4]=Array("rongyu3","",646,691);
$z[4][4]=array();
$z[4][4]['function']="cn_substr(@me,43)";

?>