<?php
$z[0]=Array("field","",56,85);
$z[0][4]=array();
$z[0][4]['name']="typename";
$z[1]=Array("channel","\r\n						<li class=\"longName\"><a href=\"[field:typeurl/]\">[field:typename/]</a></li>\r\n                    <div style=\"display:none;\">\r\n                    	{dede:field.content/}\r\n                    </div>\r\n                        ",151,418);
$z[1][4]=array();
$z[1][4]['row']="6";

?>