<?php
$z[0]=Array("field","",76,105);
$z[0][4]=array();
$z[0][4]['name']="typename";
$z[1]=Array("arclist","\r\n        <div class=\"expert\">\r\n        	<h4><span>医学科普</span><a href=\"[field:arcurl/]\">[field:title/]</a></h4>\r\n            <p><span><b class=\"reviews\"></b>条评价 <b class=\"readys\"></b>人已读</span> <span class=\"r\">发表于[field:pubdate function='GetDateMK(@me)' /]</span></p>\r\n        </div>\r\n        ",120,505);
$z[1][4]=array();
$z[1][4]['row']="3";
$z[1][4]['orderby']="rand";
$z[1][4]['titlelen']="90";

?>