<div class="zjtd_under">
									<div>
										<p>擅长</p>
										<p>领域</p>
									</div>
									<div>
										[field:scly function='cn_substr(@me,240)' /]
									</div>
								</div>
                                <div class="zjtd_time">
                                	<div>[field:czhz /]<span>[field:czsj /]</span></div>
                                    <!--<div>[field:fylx /]<span>[field:ghf /]</span></div>-->
                                    <a href="javascript:void(0)" onclick="openZoosUrl('chatwin');" style=" display: flex; align-items: center; background: #ff5f6b; border-radius: 5px; color: #fff; line-height: 2rem;width:35%;">
                                        <img src="/templets/jq/images/zjtd_zx.png" style=" width: 20%; margin: 0 7%;">
                                        立即预约
                                    </a>
                                </div>
                                
							</div>