<field:zhicheng1 itemname="职称1" autofield="1" notsend="0" type="text" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:zhicheng1>
<field:zhicheng2 itemname="职称2" autofield="1" notsend="0" type="text" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:zhicheng2>
<field:zhicheng3 itemname="职称3" autofield="1" notsend="0" type="text" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:zhicheng3>
<field:rongyu1 itemname="荣誉1" autofield="1" notsend="0" type="text" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:rongyu1>
<field:rongyu2 itemname="荣誉2" autofield="1" notsend="0" type="text" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:rongyu2>
<field:rongyu3 itemname="荣誉3" autofield="1" notsend="0" type="text" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:rongyu3>
<field:scly itemname="擅长领域" autofield="1" notsend="0" type="multitext" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:scly>
<field:zyjl itemname="执业经历" autofield="1" notsend="0" type="htmltext" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:zyjl>
<field:czhz itemname="出诊or会诊" autofield="1" notsend="0" type="text" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:czhz>
<field:czsj itemname="出诊时间" autofield="1" notsend="0" type="text" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:czsj>
<field:fylx itemname="费用类型" autofield="1" notsend="0" type="text" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:fylx>
<field:ghf itemname="费用" autofield="1" notsend="0" type="text" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:ghf>
<field:ysjy itemname="医师寄语" autofield="1" notsend="0" type="htmltext" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:ysjy>
<field:ghzx itemname="预约挂号or预约评估" autofield="1" notsend="0" type="text" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:ghzx>

<field:hdflj itemname="好大夫链接" autofield="1" notsend="0" type="text" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:hdflj>
