<img src="[field:picname/]">
							<div class="zjtd_art">
								<div class="zjtd_upper">
									<div class="zjtd_names" href="">
										<div>[field:title /]</div>
										<div>
											<p>[field:zhicheng1/]</p>
											<p>[field:zhicheng2/]</p>
											<p>[field:zhicheng3/]</p>
										</div>
									</div>
									<div class="zjtd_des">
										<div><img src="/templets/jq/images/dian.png" />[field:rongyu1 function='cn_substr(@me,43)'/]</div>
										<div><img src="/templets/jq/images/dian.png" />[field:rongyu2 function='cn_substr(@me,43)'/]</div>
										<div><img src="/templets/jq/images/dian.png" />[field:rongyu3 function='cn_substr(@me,43)'/]</div>
                                        
									</div>