
<field:zlfw itemname="诊疗范围" autofield="1" notsend="0" type="htmltext" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:zlfw>

<field:bingyin itemname="病因" autofield="1" notsend="0" type="htmltext" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:bingyin>

<field:lcbx itemname="临床表现" autofield="1" notsend="0" type="htmltext" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:lcbx>

<field:jiancha itemname="检查" autofield="1" notsend="0" type="htmltext" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:jiancha>
