<?php
$z[0]=Array("type","<a href=\"[field:typeurl/]\">[field:typename/]</a>",374,457);
$z[0][4]=array();
$z[0][4]['typeid']="65";
$z[1]=Array("type","<a href=\"[field:typeurl/]\">[field:typename/]</a>",488,570);
$z[1][4]=array();
$z[1][4]['typeid']="1";
$z[2]=Array("type","<a href=\"[field:typeurl/]\">[field:typename/]</a>",601,684);
$z[2][4]=array();
$z[2][4]['typeid']="62";
$z[3]=Array("type","<a href=\"[field:typeurl/]\">[field:typename/]</a>",715,797);
$z[3][4]=array();
$z[3][4]['typeid']="3";

?>